#!/bin/bash

OPENLAB_TOPDIR=/usr/local/openlab
source $OPENLAB_TOPDIR/Include/common.sh
source $OPENLAB_TOPDIR/Include/userop.sh
source $OPENLAB_TOPDIR/Include/boardop.sh
source $OPENLAB_TOPDIR/Include/telnetop.sh
source $OPENLAB_TOPDIR/Include/bmcop.sh
source $OPENLAB_TOPDIR/Include/board_serial_op.sh
source $OPENLAB_TOPDIR/Include/board_power_op.sh
source $OPENLAB_TOPDIR/Include/pduop.sh

board_all_no=$(grep -E "^BOARD" $OPENLAB_CONF_DIR/$BOARD_INFO_FILE | grep -Po "(?<=BOARD)([^:]*)" | tr '\n' " ")

############## Check how many boards have been used ###############################
for boardno in ${board_all_no[*]}
do
    a=$(grep -w "boardno:${boardno}" boards_used_log)
    if [ -n "$a" ];then
        boards_used[n]=$boardno
        let n=n+1
    fi
done

for boardno in ${boards_used[*]}
do
    a=$(grep -w "boardno:${boardno}" boards_used_log)

    usr=$(echo -e "$a" | grep -Po "(?<=usr:)([^ ]+)" | awk '{a[$0]++} END {for(i in a) printf("over past one week, %10s: use->%-2s times\n"), i, a[i]}' | sort)
    echo "==================================================="
    echo -e "boardno:$boardno\n${usr}"

    max_session_time=$(echo -e "$a" | grep -Po "(?<=session_time:)([^ ]+)" |awk 'BEGIN {max = 0} {if ($1+0 > max+0) max=$1} END {print max}')
    echo "max session time:${max_session_time}s"

    total_use=$(echo -e "$a" | grep -Po "(?<=total_use:)([^ ]+)" | awk 'BEGIN {max = 0} {if ($1+0 > max+0) max=$1} END {print max}')
    echo "total using time:${total_use}s"

    total_time=$(echo -e "$a" | grep -Po "(?<=total_time:)([^ ]+)" | awk 'BEGIN {max = 0} {if ($1+0 > max+0) max=$1} END {print max}')
    echo "total time:${total_time}s"

    rating=$(echo -e "$a" | grep -P "(?<=total_use:)${total_use}" | grep -Po "(?<=rating:)([^ ]+)")
    echo -e "rating:\n${rating}"
done

