#!/bin/bash

OPENLAB_TOPDIR=/usr/local/openlab
source $OPENLAB_TOPDIR/Include/common.sh
source $OPENLAB_TOPDIR/Include/userop.sh
source $OPENLAB_TOPDIR/Include/boardop.sh
source $OPENLAB_TOPDIR/Include/telnetop.sh
source $OPENLAB_TOPDIR/Include/bmcop.sh
source $OPENLAB_TOPDIR/Include/board_serial_op.sh
source $OPENLAB_TOPDIR/Include/board_power_op.sh
source $OPENLAB_TOPDIR/Include/pduop.sh

:> boards_used_log
echo -e "We start to test at `date`" >> boards_used_log

board_all_no=$(grep -E "^BOARD" $OPENLAB_CONF_DIR/$BOARD_INFO_FILE | grep -Po "(?<=BOARD)([^:]*)" | tr '\n' " ")
board_all_cur_usr=$(cut -d ":" -f1 $OPENLAB_CONF_DIR/$USER_INFO_FILE | grep ^[a-zA-Z]|tr '\n' " ")

for boardno in ${board_all_no[*]}
do
    declare -A board_$boardno
    boardinfo=board_$boardno
    eval $boardinfo=\([cur_usr]="" [status]=0 [start_time]=0 [session_start]=0 [session_end]=0 [session_time]=0 [total_use]=0 [total_time]=0\)
    eval $boardinfo[start_time]=$(date +%s)
done

while true
do
    for boardno in ${board_all_no[*]}
    do
        boardinfo=board_$boardno
        boardtype=$(get_board_type $boardno)
        cur_usr=$(get_board_current_user $boardno)

        if [[ x"$cur_usr" != x"" && x"$(eval echo \${$boardinfo[cur_usr]})" == x"" ]]; then
            eval $boardinfo[status]=1
            eval $boardinfo[cur_usr]=$cur_usr
            eval $boardinfo[session_start]=$(date +%s)
        elif [[ x"$cur_usr" == x"" && "$(eval echo \${$boardinfo[status]})" == "1" ]]; then
        #elif [[ "$(eval echo \${${boardinfo}[status]})" == "1" ]]; then # for testing
            eval $boardinfo[status]=0
            eval $boardinfo[session_end]=$(date +%s)
            eval let $boardinfo[session_time]=\${$boardinfo[session_end]}-\${$boardinfo[session_start]}
            eval let $boardinfo[total_use]+=\${$boardinfo[session_time]}
            eval let $boardinfo[total_time]=\${$boardinfo[session_end]}-\${$boardinfo[start_time]}
            echo "-----------------------------------------------------------------------------------------------" >> boards_used_log
            printf "boardno:%-6s boardtype: %-6s start_time:%-6s usr:%-6s session_start:%-6s session_end:%-6s session_time:%-6s total_use:%-6s total_time:%-6s rating:%-6s\n" \
                $boardno \
                $boardtype \
                $(eval echo \${$boardinfo[start_time]}) \
                $(eval echo \${$boardinfo[cur_usr]}) \
                $(eval echo \${$boardinfo[session_start]}) \
                $(eval echo \${$boardinfo[session_end]}) \
                $(eval echo \${$boardinfo[session_time]}) \
                $(eval echo \${$boardinfo[total_use]}) \
                $(eval echo \${$boardinfo[total_time]}) \
                $(awk 'BEGIN{printf "%.2f\n",'$(eval echo \${$boardinfo[total_use]}/\${$boardinfo[total_time]})'}') >> boards_used_log
            eval $boardinfo[cur_usr]=""
        fi
    done

    sleep 10
done

